enabled: true

name: service-portal
namespace: service-portal
image:
    name: 722069360300.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/service-portal
    version: latest
imagePullSecrets: 
  - name: service-portal-ecr
imagePullPolicy: IfNotPresent
replicas: 1

volumeMounts:
    application: []

##########################
# Local volumes
##########################
volumes:
    - name: timezone
      hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
    - name: log-volume
      emptyDir: {}
      
# Service
service:
    type: NodePort
    annotations:
        nil: nil
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
        - name: https
          port: 443
          targetPort: 80
          protocol: TCP

# Ingress
ingress:
  enabled: false
  annotations:
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0 # replace or leave out
      alb.ingress.kubernetes.io/scheme: "internet-facing" # internet-facing
      alb.ingress.kubernetes.io/target-type: instance # Your console and console-api should be NodePort for this configuration.
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:... # This should be replaced with your cert arn.
      external-dns.alpha.kubernetes.io/hostname: "demo.spaceone.megazone.io"

####################################
# pod spec (append more pod spec)
# example nodeSelect
#
# pod:
#   spec:
#     nodeSelector:
#       application: my-node-group
####################################
pod:
    spec: {}