import type { NextPage } from 'next';
import Head from 'next/head';
import Example from '../components/layouts/example';

const Home: NextPage = () => (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>hello index</h2>
        <Example />
    </div>
);

export default Home;
